# Generated by Django 5.1.4 on 2025-01-12 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GeographyData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=100, verbose_name='Город')),
                ('average_salary', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Средняя зарплата')),
                ('vacancy_share', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Доля вакансий')),
                ('year', models.IntegerField(verbose_name='Год')),
                ('is_general', models.BooleanField(default=True, verbose_name='Общая статистика')),
            ],
            options={
                'verbose_name': 'География',
                'verbose_name_plural': 'География',
                'ordering': ['-average_salary'],
            },
        ),
        migrations.CreateModel(
            name='Graph',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('image', models.ImageField(upload_to='graphs/', verbose_name='График')),
                ('graph_type', models.CharField(choices=[('salary', 'График зарплат'), ('counts', 'График количества вакансий'), ('skills', 'График навыков'), ('geography', 'График географии')], max_length=20, verbose_name='Тип графика')),
                ('year', models.IntegerField(blank=True, null=True, verbose_name='Год')),
                ('is_general', models.BooleanField(default=True, verbose_name='Общая статистика')),
            ],
            options={
                'verbose_name': 'График',
                'verbose_name_plural': 'Графики',
                'ordering': ['graph_type', 'year'],
            },
        ),
        migrations.CreateModel(
            name='LastVacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название вакансии')),
                ('description', models.TextField(verbose_name='Описание вакансии')),
                ('skills', models.TextField(verbose_name='Навыки')),
                ('company', models.CharField(max_length=200, verbose_name='Компания')),
                ('salary_from', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Зарплата от')),
                ('salary_to', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Зарплата до')),
                ('region', models.CharField(max_length=100, verbose_name='Регион')),
                ('published_at', models.DateTimeField(verbose_name='Дата публикации')),
            ],
            options={
                'verbose_name': 'Последняя вакансия',
                'verbose_name_plural': 'Последние вакансии',
                'ordering': ['-published_at'],
            },
        ),
        migrations.CreateModel(
            name='MainPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('description', models.TextField(verbose_name='Описание профессии')),
                ('image', models.ImageField(upload_to='profession_images/', verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'Главная страница',
                'verbose_name_plural': 'Главная страница',
            },
        ),
        migrations.CreateModel(
            name='SalaryStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(verbose_name='Год')),
                ('average_salary', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Средняя зарплата')),
                ('vacancy_count', models.IntegerField(verbose_name='Количество вакансий')),
                ('is_general', models.BooleanField(default=True, verbose_name='Общая статистика')),
            ],
            options={
                'verbose_name': 'Статистика зарплат',
                'verbose_name_plural': 'Статистика зарплат',
                'ordering': ['year'],
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название навыка')),
                ('year', models.IntegerField(verbose_name='Год')),
                ('count', models.IntegerField(verbose_name='Количество упоминаний')),
            ],
            options={
                'verbose_name': 'Навык',
                'verbose_name_plural': 'Навыки',
                'ordering': ['-year', '-count'],
            },
        ),
    ]
