# Generated by Django 5.1.4 on 2025-01-14 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_skill_options_skill_is_general'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainpage',
            name='title',
            field=models.CharField(default='PHP-программист', max_length=200, verbose_name='Заголовок'),
        ),
    ]
